//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asaal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewsKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewsKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asaal.Resources.ViewsKeys", typeof(ViewsKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please confirm your account by clicking the following link .
        /// </summary>
        public static string accountConfirmationEmailbBodyP {
            get {
                return ResourceManager.GetString("accountConfirmationEmailbBodyP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email From.
        /// </summary>
        public static string accountConfirmationEmailFooterP1 {
            get {
                return ResourceManager.GetString("accountConfirmationEmailFooterP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We send this email because U Are Register on Our site, if You Dont All U Need is just ignore this email 😃.
        /// </summary>
        public static string accountConfirmationEmailFooterP2 {
            get {
                return ResourceManager.GetString("accountConfirmationEmailFooterP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your account.
        /// </summary>
        public static string accountConfirmationEmailSubject {
            get {
                return ResourceManager.GetString("accountConfirmationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Replay.
        /// </summary>
        public static string addReplay {
            get {
                return ResourceManager.GetString("addReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Admins.
        /// </summary>
        public static string addToAdmins {
            get {
                return ResourceManager.GetString("addToAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Supervisors.
        /// </summary>
        public static string addToSupervisors {
            get {
                return ResourceManager.GetString("addToSupervisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi ther, if you want to Add Yor Advertise here you just need to.
        /// </summary>
        public static string addYourAdMsg {
            get {
                return ResourceManager.GetString("addYourAdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string admins {
            get {
                return ResourceManager.GetString("admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already have an account.
        /// </summary>
        public static string alreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("alreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your answer Here .....
        /// </summary>
        public static string answerPlaceholder {
            get {
                return ResourceManager.GetString("answerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers.
        /// </summary>
        public static string answers {
            get {
                return ResourceManager.GetString("answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers with Replays.
        /// </summary>
        public static string answersWithReplays {
            get {
                return ResourceManager.GetString("answersWithReplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asaal.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best users in Socitey.
        /// </summary>
        public static string bestUsersInThisSocitey {
            get {
                return ResourceManager.GetString("bestUsersInThisSocitey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Default Language.
        /// </summary>
        public static string changeDefaultLanguage {
            get {
                return ResourceManager.GetString("changeDefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Favicon.
        /// </summary>
        public static string changeFavicon {
            get {
                return ResourceManager.GetString("changeFavicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Favicon and Logo.
        /// </summary>
        public static string changeFaviconAndLogo {
            get {
                return ResourceManager.GetString("changeFaviconAndLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, you should choose favicon before bress button..
        /// </summary>
        public static string changeFaviconErrorMsg {
            get {
                return ResourceManager.GetString("changeFaviconErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose favicon with &apos;ico&apos; format.
        /// </summary>
        public static string changeFaviconLabel {
            get {
                return ResourceManager.GetString("changeFaviconLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the icon you are going to choose should be in &apos;ico&apos; format and fyi icon place is in the top of browser side by side with title.
        /// </summary>
        public static string changeFaviconNote {
            get {
                return ResourceManager.GetString("changeFaviconNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the language you are going to choose it is display langauage of site every thing exept content of users, and this option is to admins to have Ability to change display language and targeting specific community.
        /// </summary>
        public static string changeLanguageNote {
            get {
                return ResourceManager.GetString("changeLanguageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change Logo.
        /// </summary>
        public static string changeLogo {
            get {
                return ResourceManager.GetString("changeLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry you should choose logo before bress button..
        /// </summary>
        public static string changeLogoErrorMsg {
            get {
                return ResourceManager.GetString("changeLogoErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the logo you are going to choose is better to be in &apos;png&apos; format and it is better to make its size in 40*150 in pixels and logo place is in the first element in the navbar.
        /// </summary>
        public static string changeLogoNote {
            get {
                return ResourceManager.GetString("changeLogoNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Profile picture.
        /// </summary>
        public static string changeProfilePicture {
            get {
                return ResourceManager.GetString("changeProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Country.
        /// </summary>
        public static string chooseCountry {
            get {
                return ResourceManager.GetString("chooseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Logo.
        /// </summary>
        public static string chooseLogo {
            get {
                return ResourceManager.GetString("chooseLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Society.
        /// </summary>
        public static string chooseSociety {
            get {
                return ResourceManager.GetString("chooseSociety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your New picture.
        /// </summary>
        public static string chooseYourPicture {
            get {
                return ResourceManager.GetString("chooseYourPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string confirmEmail {
            get {
                return ResourceManager.GetString("confirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please.
        /// </summary>
        public static string confirmEmailMsg {
            get {
                return ResourceManager.GetString("confirmEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string confirmPasswordErrorMsg {
            get {
                return ResourceManager.GetString("confirmPasswordErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string contactUs {
            get {
                return ResourceManager.GetString("contactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string controlPanel {
            get {
                return ResourceManager.GetString("controlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give This User More Validities.
        /// </summary>
        public static string cPanelAddToRoleHeading {
            get {
                return ResourceManager.GetString("cPanelAddToRoleHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this user forever.
        /// </summary>
        public static string cPanelDeleteUserHeading {
            get {
                return ResourceManager.GetString("cPanelDeleteUserHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string currentPassword {
            get {
                return ResourceManager.GetString("currentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete | Be Careful.
        /// </summary>
        public static string deleteModalHeader {
            get {
                return ResourceManager.GetString("deleteModalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure you want to delete this, Remember if you Confirm Delete you cant restore it..
        /// </summary>
        public static string deleteWarningMsg {
            get {
                return ResourceManager.GetString("deleteWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed with.
        /// </summary>
        public static string developedWith {
            get {
                return ResourceManager.GetString("developedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farouk Abdelhamid.
        /// </summary>
        public static string developerName {
            get {
                return ResourceManager.GetString("developerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admins are people can control in every thing in the site Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used..
        /// </summary>
        public static string discriptionOfAdmins {
            get {
                return ResourceManager.GetString("discriptionOfAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admins are people can control in every thing in the site Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used..
        /// </summary>
        public static string discriptionOfSupervisors {
            get {
                return ResourceManager.GetString("discriptionOfSupervisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admins are people can control in every thing in the site Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used..
        /// </summary>
        public static string discriptionOfUsers {
            get {
                return ResourceManager.GetString("discriptionOfUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don`t have an account?.
        /// </summary>
        public static string dontHaveAccount {
            get {
                return ResourceManager.GetString("dontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vote.
        /// </summary>
        public static string doVote {
            get {
                return ResourceManager.GetString("doVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update or Delete you Question:.
        /// </summary>
        public static string editYourQuestion {
            get {
                return ResourceManager.GetString("editYourQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this email is not valid.
        /// </summary>
        public static string emailNotValid {
            get {
                return ResourceManager.GetString("emailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Page.
        /// </summary>
        public static string errorPage {
            get {
                return ResourceManager.GetString("errorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string errorPageParagraph {
            get {
                return ResourceManager.GetString("errorPageParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your email is not confirmed for that you cant reset your password.
        /// </summary>
        public static string faildToResetPasswordErrorMsg {
            get {
                return ResourceManager.GetString("faildToResetPasswordErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Admins Onlay.
        /// </summary>
        public static string forAdminsOnlay {
            get {
                return ResourceManager.GetString("forAdminsOnlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string forgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("forgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to our team send to you an email to your Email address, Please check your email to reset your password..
        /// </summary>
        public static string forgotPasswordConfirmationMsg {
            get {
                return ResourceManager.GetString("forgotPasswordConfirmationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you are actully forget your password all you have is just to write your email wich you are used in sign up  and you will resive an email make you able to reset your password .
        /// </summary>
        public static string forgotPasswordInfoMsg {
            get {
                return ResourceManager.GetString("forgotPasswordInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string forgotYourPassword {
            get {
                return ResourceManager.GetString("forgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High View Questions.
        /// </summary>
        public static string highViewQuestions {
            get {
                return ResourceManager.GetString("highViewQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address or password is not correct. Please try again..
        /// </summary>
        public static string incorrectEmailOrPasswordMsg {
            get {
                return ResourceManager.GetString("incorrectEmailOrPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Answers.
        /// </summary>
        public static string lastAnswers {
            get {
                return ResourceManager.GetString("lastAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Answers in this Socitey.
        /// </summary>
        public static string lastAnswersInThisSocitey {
            get {
                return ResourceManager.GetString("lastAnswersInThisSocitey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in here.
        /// </summary>
        public static string loginHere {
            get {
                return ResourceManager.GetString("loginHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string logOff {
            get {
                return ResourceManager.GetString("logOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your fullname should be low than 50 charcters.
        /// </summary>
        public static string max50 {
            get {
                return ResourceManager.GetString("max50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your fullname should be at least 4 charcters.
        /// </summary>
        public static string min4 {
            get {
                return ResourceManager.GetString("min4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Active.
        /// </summary>
        public static string mostActive {
            get {
                return ResourceManager.GetString("mostActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Question.
        /// </summary>
        public static string newQuestion {
            get {
                return ResourceManager.GetString("newQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Society.
        /// </summary>
        public static string newSociety {
            get {
                return ResourceManager.GetString("newSociety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string notification {
            get {
                return ResourceManager.GetString("notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  add a Answer in your question.
        /// </summary>
        public static string notification4newAnswer2questionOwner {
            get {
                return ResourceManager.GetString("notification4newAnswer2questionOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  add a replay to your answer.
        /// </summary>
        public static string notification4newReplay2answerOwner {
            get {
                return ResourceManager.GetString("notification4newReplay2answerOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  add a replay to a answer in your question.
        /// </summary>
        public static string notification4newReplay2questionOwner {
            get {
                return ResourceManager.GetString("notification4newReplay2questionOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string notifications {
            get {
                return ResourceManager.GetString("notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        public static string publishDate {
            get {
                return ResourceManager.GetString("publishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to questions.
        /// </summary>
        public static string questions {
            get {
                return ResourceManager.GetString("questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, you can use  [gmail, hotmail, outlook, yahoo] Onlay.
        /// </summary>
        public static string RealEmailErrMsg {
            get {
                return ResourceManager.GetString("RealEmailErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register here.
        /// </summary>
        public static string registerHere {
            get {
                return ResourceManager.GetString("registerHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember !.
        /// </summary>
        public static string remember {
            get {
                return ResourceManager.GetString("remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Account.
        /// </summary>
        public static string removeAccount {
            get {
                return ResourceManager.GetString("removeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be careful, you are going to delete this user Are you sure?.
        /// </summary>
        public static string removeAccountWarningMsg {
            get {
                return ResourceManager.GetString("removeAccountWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Admins.
        /// </summary>
        public static string removeFromAdmins {
            get {
                return ResourceManager.GetString("removeFromAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from supervisiors.
        /// </summary>
        public static string removeFromSupervisiors {
            get {
                return ResourceManager.GetString("removeFromSupervisiors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay.
        /// </summary>
        public static string replay {
            get {
                return ResourceManager.GetString("replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your Replay Here .....
        /// </summary>
        public static string replayPlaceholder {
            get {
                return ResourceManager.GetString("replayPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is Required.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string resetPassword {
            get {
                return ResourceManager.GetString("resetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string resetPasswordConfirmation {
            get {
                return ResourceManager.GetString("resetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please.
        /// </summary>
        public static string resetPasswordConfirmationMsg {
            get {
                return ResourceManager.GetString("resetPasswordConfirmationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to reset your password Please click next Reset Password button.
        /// </summary>
        public static string resetPasswordEmailbBodyP {
            get {
                return ResourceManager.GetString("resetPasswordEmailbBodyP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email From.
        /// </summary>
        public static string resetPasswordEmailFooterP1 {
            get {
                return ResourceManager.GetString("resetPasswordEmailFooterP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We send this email to you because we recive  a request to reset your password account , if is not you All U Need is just ignore this email 😃.
        /// </summary>
        public static string resetPasswordEmailFooterP2 {
            get {
                return ResourceManager.GetString("resetPasswordEmailFooterP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your Password.
        /// </summary>
        public static string resetPasswordEmailSubject {
            get {
                return ResourceManager.GetString("resetPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me Email.
        /// </summary>
        public static string sendEmail {
            get {
                return ResourceManager.GetString("sendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Emails by site .
        /// </summary>
        public static string sendEmailsBySite {
            get {
                return ResourceManager.GetString("sendEmailsBySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Emails or Not.
        /// </summary>
        public static string SendEmailsOrNot {
            get {
                return ResourceManager.GetString("SendEmailsOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string share {
            get {
                return ResourceManager.GetString("share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you want to add a answer please.
        /// </summary>
        public static string signToAnswerMsg {
            get {
                return ResourceManager.GetString("signToAnswerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing in to Add Replay.
        /// </summary>
        public static string SingToAddReplay {
            get {
                return ResourceManager.GetString("SingToAddReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asaal is a good place to add your question and another users add there answers.
        /// </summary>
        public static string siteDescription4meta {
            get {
                return ResourceManager.GetString("siteDescription4meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Domain.
        /// </summary>
        public static string siteDomain {
            get {
                return ResourceManager.GetString("siteDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Societies.
        /// </summary>
        public static string societies {
            get {
                return ResourceManager.GetString("societies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to society.
        /// </summary>
        public static string society {
            get {
                return ResourceManager.GetString("society", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here our website going to get the society wich have greater number of questions.
        /// </summary>
        public static string societyHeroPlaceholder {
            get {
                return ResourceManager.GetString("societyHeroPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when you create new sciety you cant remove it and beacause when you remove it every question related with this society will deleted too , but you can edit it  .
        /// </summary>
        public static string societyNote {
            get {
                return ResourceManager.GetString("societyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry we dont find any thing yet.
        /// </summary>
        public static string sorryMsg {
            get {
                return ResourceManager.GetString("sorryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your charchters should be between 100 at least and 1000 .
        /// </summary>
        public static string stringLength100_1000 {
            get {
                return ResourceManager.GetString("stringLength100_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your charchters should be between 150 at least and 250.
        /// </summary>
        public static string stringLength150_250 {
            get {
                return ResourceManager.GetString("stringLength150_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your charchters should be between 150 at least and 500.
        /// </summary>
        public static string stringLength150_500 {
            get {
                return ResourceManager.GetString("stringLength150_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your charchters should be between 20 at least and 250.
        /// </summary>
        public static string stringLength20_250 {
            get {
                return ResourceManager.GetString("stringLength20_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your charchters should be between 4 at least and 100.
        /// </summary>
        public static string stringLength4_100 {
            get {
                return ResourceManager.GetString("stringLength4_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your charchters should be between 5 at least and 1000.
        /// </summary>
        public static string stringLength5_1000 {
            get {
                return ResourceManager.GetString("stringLength5_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your password should be between 6 at least and 100.
        /// </summary>
        public static string stringLength6_100 {
            get {
                return ResourceManager.GetString("stringLength6_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your password is changed succesfully.
        /// </summary>
        public static string succesChangePasswordMsg {
            get {
                return ResourceManager.GetString("succesChangePasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your picture is changed succesfully.
        /// </summary>
        public static string succesChangePhotoMsg {
            get {
                return ResourceManager.GetString("succesChangePhotoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your information is updated succesfully.
        /// </summary>
        public static string succesUpdateProfileMsg {
            get {
                return ResourceManager.GetString("succesUpdateProfileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this setting is updated succesfully.
        /// </summary>
        public static string succesUpdateSendEmailOrNotMsg {
            get {
                return ResourceManager.GetString("succesUpdateSendEmailOrNotMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to site domain is updated succesfully..
        /// </summary>
        public static string succesUpdateSiteDomainMsg {
            get {
                return ResourceManager.GetString("succesUpdateSiteDomainMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to site email and password are updated succesfully..
        /// </summary>
        public static string succesUpdateSiteEmailMsg {
            get {
                return ResourceManager.GetString("succesUpdateSiteEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisior.
        /// </summary>
        public static string supervisior {
            get {
                return ResourceManager.GetString("supervisior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisiors.
        /// </summary>
        public static string supervisiors {
            get {
                return ResourceManager.GetString("supervisiors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update my Info.
        /// </summary>
        public static string updateMyInfo {
            get {
                return ResourceManager.GetString("updateMyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here you can make site send emails or not to confirme users accounts.
        /// </summary>
        public static string updateSendEmailOrNotNote {
            get {
                return ResourceManager.GetString("updateSendEmailOrNotNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Site Domain.
        /// </summary>
        public static string updateSiteDomain {
            get {
                return ResourceManager.GetString("updateSiteDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available..
        /// </summary>
        public static string updateSiteDomainNote {
            get {
                return ResourceManager.GetString("updateSiteDomainNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Site Email.
        /// </summary>
        public static string updateSiteEmail {
            get {
                return ResourceManager.GetString("updateSiteEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this email is using to sent emails to site users toconfirme accounts and reset passowrd , please make sure you are enter right data untel nothing happend while sent emails ..
        /// </summary>
        public static string updateSiteEmailNote {
            get {
                return ResourceManager.GetString("updateSiteEmailNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Site Setting.
        /// </summary>
        public static string updateSiteSetting {
            get {
                return ResourceManager.GetString("updateSiteSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you cant vote in your answer.
        /// </summary>
        public static string userOwnTheAnswerMsg {
            get {
                return ResourceManager.GetString("userOwnTheAnswerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string views {
            get {
                return ResourceManager.GetString("views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, you can use arabic and english only.
        /// </summary>
        public static string vlaidFullNameMsg {
            get {
                return ResourceManager.GetString("vlaidFullNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes.
        /// </summary>
        public static string votes {
            get {
                return ResourceManager.GetString("votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, you cant vote again in answer before remove your vote first.
        /// </summary>
        public static string youCantVoteAgainMsg {
            get {
                return ResourceManager.GetString("youCantVoteAgainMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, if you want to vote you should login first.
        /// </summary>
        public static string youCantVoteMsg {
            get {
                return ResourceManager.GetString("youCantVoteMsg", resourceCulture);
            }
        }
    }
}
